CREATE DATABASE IF NOT EXISTS `1383838`;
USE `1383838`;

CREATE TABLE IF NOT EXISTS uploads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_pin VARCHAR(4) NOT NULL UNIQUE,
    file_name VARCHAR(255) NOT NULL,
    file_content LONGBLOB,
    storage_path VARCHAR(255) NULL,
    encryption_iv VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS text_shares (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pin VARCHAR(4) NOT NULL UNIQUE,
    content LONGTEXT NOT NULL,
    iv VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
